#%RAML 1.0 NamedExample
{
   "application" : "Marketing XAPI",
   "env" : "dev",
   "mtransactionId" : "1bc39740-859a-11e8-9411-eefd20524153",
   "code": "500",
   "timeStamp": "2022-09-30T15:27:49.274Z",
   "message": "Internal Server Error",
   "description" : "The server was unable to process the request due to an internal error"  
}
