#%RAML 1.0 NamedExample
assets:
  - 
    name: HyperX FURY USB
    type: Web assets
    lang: English
    location: FLASH MEMORY > USB > Differentiated
    downloaddate: 2014-9-30T00:00:00Z
    expirationdate: 2014-9-30T00:00:00Z
    createddate: 2014-9-30T00:00:00Z
    modifieddate: 2014-9-30T00:00:00Z
    ppsite: Kingston_en
    email: lking@kingston.eu
  - 
    name: HyperX FURY USB
    type: Web assets
    lang: German
    location: FLASH MEMORY > USB > Differentiated
    downloaddate: 2014-9-30T00:00:00Z
    expirationdate: 2014-9-30T00:00:00Z
    createddate: 2014-9-30T00:00:00Z
    modifieddate: 2014-9-30T00:00:00Z
    ppsite: Kingston_en
    email: lking@kingston.eu    