#%RAML 1.0 NamedExample
{
  "firstName" : "peter",
  "lastName" : "li",
  "email" : "peter_li@le.com",
  "accountName" : "company name",
  "language" : "english",
  "jobTitle" : "Sales Manager",
  "productPreferences" : "HyperX Memory",
  "country" : "Germany",
  "accountType" : "distributor",
  "accountProfile" : "Gold,Partner"
}






